name: Build macOS Application

on:
  push:
    tags:
      - 'v*'  # 仅推送 tag 时触发
  workflow_dispatch:     # 支持手动触发

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build with pyinstaller
        run: pyinstaller run_app.py --onefile --noconfirm --clean --collect-all=streamlit --add-data="app.py:."

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-app
          path: dist/run_app

      - name: List output
        run: ls dist

      # ✅ 只有当是 tag 推送时，才执行 Release 上传
      - name: Upload to GitHub Releases (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/run_app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}